### ISSUE TITLE
Question about EncT5 framework

### ISSUE THREAD

**Issue by boscoj2008** [osainz59/t5-encoder#2]
Hello? The paper talks about a **12-Layer** encoder- **(1-Layer)** decoder setting but in the repository example, you have elaborated this for an encoder-only model. Is there something I did not understand? How can the pooling be performed on the encoder-only model when the paper mentions a limitation of the [CLS] not being seen in pre-training as well as the sub-optimality of pooling with either mean or max pooling? I appreciate your feedback.

```
import t5_encoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("google/t5-v1_1-base")
model = AutoModelForSequenceClassification.from_pretrained("google/t5-v1_1-base")
model
```

**Comment by osainz59** [comment]
Hi @boscoj2008 ,

Maybe there was a misunderstanding, this code is not a re-implementation of the papers but an implementation from scratch. It is heavily inspired in both papers but also includes significant architecture changes. That being said, the `AutoModelForSequenceClassification` class uses the end of sentence `</s>` token representation as if it was the `[CLS]` token. At the end it works on a similar way, for instance, on a RoBERTa model the `[CLS]` or start of sentence `<s>` token is never used during pre-training, the same happends to the `</s>`. And as the encoders are bidirectional there is no real problem with that. Also the results suggest that the model is able to match its encoder-decoder counterpart following this approach.

BTW, I am not an author of any of those papers.

Let me know if you have more questions,
Oscar

**Comment by boscoj2008** [comment]
Thanks, Oscar for reaching out. Yes, indeed you're right about the approach used in RoBERTa being similar to T5. I will look at it again and get back if I have further questions. Cheers!
